package services

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"time"

	"github.com/Fr33raNg3r/RProxy/client/webui-backend/config"
)

// ----------------- 服务端密钥 -----------------

func ReadServerPrivateKey() (string, error) {
	b, err := os.ReadFile(config.WGServerPrivKey)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(b)), nil
}

func ReadServerPublicKey() (string, error) {
	b, err := os.ReadFile(config.WGServerPubKey)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(b)), nil
}

// ----------------- 客户端密钥 -----------------

func GenerateKeyPair() (priv, pub string, err error) {
	out, err := exec.Command("wg", "genkey").Output()
	if err != nil {
		return "", "", fmt.Errorf("wg genkey: %w", err)
	}
	priv = strings.TrimSpace(string(out))

	cmd := exec.Command("wg", "pubkey")
	cmd.Stdin = strings.NewReader(priv)
	pubBytes, err := cmd.Output()
	if err != nil {
		return "", "", fmt.Errorf("wg pubkey: %w", err)
	}
	pub = strings.TrimSpace(string(pubBytes))
	return
}

func GeneratePresharedKey() (string, error) {
	out, err := exec.Command("wg", "genpsk").Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// ----------------- 渲染服务端 wg0.conf -----------------

func RenderWGConfig(cfg *config.WebUIConfig, peers []config.WGPeer) error {
	priv, err := ReadServerPrivateKey()
	if err != nil {
		return fmt.Errorf("读取服务端私钥: %w", err)
	}

	subnet := cfg.WGSubnet
	if subnet == "" {
		subnet = "172.16.7.0/24"
	}
	serverAddr, err := wgServerAddress(subnet)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "# Auto-generated by RProxy WebUI - DO NOT EDIT MANUALLY\n")
	fmt.Fprintf(&buf, "[Interface]\n")
	fmt.Fprintf(&buf, "PrivateKey = %s\n", priv)
	fmt.Fprintf(&buf, "Address = %s\n", serverAddr)
	fmt.Fprintf(&buf, "ListenPort = %d\n", cfg.WGListenPort)
	fmt.Fprintf(&buf, "SaveConfig = false\n")
	fmt.Fprintf(&buf, "PostUp = sysctl -w net.ipv4.ip_forward=1\n\n")

	for _, p := range peers {
		fmt.Fprintf(&buf, "# Peer: %s (id=%s)\n", p.Name, p.ID)
		fmt.Fprintf(&buf, "[Peer]\n")
		fmt.Fprintf(&buf, "PublicKey = %s\n", p.PublicKey)
		if p.PresharedKey != "" {
			fmt.Fprintf(&buf, "PresharedKey = %s\n", p.PresharedKey)
		}
		fmt.Fprintf(&buf, "AllowedIPs = %s\n\n", p.Address)
	}

	if err := os.MkdirAll("/etc/wireguard", 0700); err != nil {
		return err
	}
	tmp := config.WGConfPath + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0600); err != nil {
		return err
	}
	return os.Rename(tmp, config.WGConfPath)
}

// 计算服务端地址：x.x.x.1/<前缀>
func wgServerAddress(subnet string) (string, error) {
	ip, ipnet, err := net.ParseCIDR(subnet)
	if err != nil {
		return "", err
	}
	ip4 := ip.To4()
	if ip4 == nil {
		return "", fmt.Errorf("仅支持 IPv4 子网")
	}
	mask, _ := ipnet.Mask.Size()
	srv := net.IPv4(ip4[0], ip4[1], ip4[2], 1)
	return fmt.Sprintf("%s/%d", srv.String(), mask), nil
}

func wgServerIPOnly(subnet string) string {
	ip, _, err := net.ParseCIDR(subnet)
	if err != nil {
		return "172.16.7.1"
	}
	ip4 := ip.To4()
	if ip4 == nil {
		return "172.16.7.1"
	}
	return fmt.Sprintf("%d.%d.%d.1", ip4[0], ip4[1], ip4[2])
}

// AllocatePeerIP 在子网内分配下一个空闲 IP（.2 - .254）
func AllocatePeerIP(subnet string, used []string) (string, error) {
	_, ipnet, err := net.ParseCIDR(subnet)
	if err != nil {
		return "", err
	}
	usedSet := map[string]bool{}
	for _, u := range used {
		usedSet[strings.Split(u, "/")[0]] = true
	}
	base := ipnet.IP.To4()
	for i := 2; i < 254; i++ {
		ip := net.IPv4(base[0], base[1], base[2], byte(i))
		if !usedSet[ip.String()] {
			return fmt.Sprintf("%s/32", ip.String()), nil
		}
	}
	return "", fmt.Errorf("WG 子网已无可用 IP")
}

// ----------------- WG 服务管理 -----------------

func RestartWG() error {
	_ = exec.Command("systemctl", "stop", "wg-quick@wg0").Run()
	if err := exec.Command("systemctl", "start", "wg-quick@wg0").Run(); err != nil {
		return err
	}
	return exec.Command("systemctl", "enable", "wg-quick@wg0").Run()
}

func StopWG() error {
	return exec.Command("systemctl", "stop", "wg-quick@wg0").Run()
}

// ----------------- 流量统计 -----------------

type PeerTransfer struct {
	PeerPublicKey string
	RxBytes       uint64
	TxBytes       uint64
}

// GetWGTransfers 解析 `wg show wg0 transfer`
// 输出格式：<pubkey>\t<rx>\t<tx>
func GetWGTransfers() ([]PeerTransfer, error) {
	out, err := exec.Command("wg", "show", config.WGInterface, "transfer").Output()
	if err != nil {
		return []PeerTransfer{}, nil // wg 可能未启动，返回空
	}
	var result []PeerTransfer
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	for _, line := range lines {
		fields := strings.Fields(line)
		if len(fields) != 3 {
			continue
		}
		rx, _ := strconv.ParseUint(fields[1], 10, 64)
		tx, _ := strconv.ParseUint(fields[2], 10, 64)
		result = append(result, PeerTransfer{
			PeerPublicKey: fields[0],
			RxBytes:       rx,
			TxBytes:       tx,
		})
	}
	return result, nil
}

// PeerSpeedSampler 维护两次采样间的速度差，单位 KB/s
type PeerSpeedSampler struct {
	last     map[string]PeerTransfer
	lastTime time.Time
}

func NewPeerSpeedSampler() *PeerSpeedSampler {
	return &PeerSpeedSampler{last: map[string]PeerTransfer{}}
}

type PeerSpeed struct {
	PublicKey string `json:"public_key"`
	RxKBps    uint64 `json:"rx_kbps"`
	TxKBps    uint64 `json:"tx_kbps"`
}

// Sample 采样一次并返回相对上一次的速度（KB/s）
// 第一次调用建立基线，返回空 list
func (s *PeerSpeedSampler) Sample() ([]PeerSpeed, error) {
	current, err := GetWGTransfers()
	if err != nil {
		return nil, err
	}
	now := time.Now()

	defer func() {
		s.last = map[string]PeerTransfer{}
		for _, t := range current {
			s.last[t.PeerPublicKey] = t
		}
		s.lastTime = now
	}()

	if s.lastTime.IsZero() {
		return []PeerSpeed{}, nil
	}
	dt := now.Sub(s.lastTime).Seconds()
	if dt <= 0 {
		return []PeerSpeed{}, nil
	}

	result := make([]PeerSpeed, 0, len(current))
	for _, t := range current {
		prev, ok := s.last[t.PeerPublicKey]
		if !ok {
			result = append(result, PeerSpeed{PublicKey: t.PeerPublicKey})
			continue
		}
		var rx, tx uint64
		if t.RxBytes > prev.RxBytes {
			rx = uint64(float64(t.RxBytes-prev.RxBytes) / dt / 1024)
		}
		if t.TxBytes > prev.TxBytes {
			tx = uint64(float64(t.TxBytes-prev.TxBytes) / dt / 1024)
		}
		result = append(result, PeerSpeed{
			PublicKey: t.PeerPublicKey,
			RxKBps:    rx,
			TxKBps:    tx,
		})
	}
	return result, nil
}

// ----------------- 客户端配置文本 -----------------

func BuildClientConfig(cfg *config.WebUIConfig, peer config.WGPeer, serverEndpointHost string) (string, error) {
	srvPub, err := ReadServerPublicKey()
	if err != nil {
		return "", err
	}
	srvDNSIP := wgServerIPOnly(cfg.WGSubnet)

	// 客户端的 [Interface] Address 必须用整个 WG 子网的掩码（如 /24），
	// 否则客户端不知道 172.16.7.1（服务端 wg0 IP）在同一个子网，
	// 路由表缺失导致包死在客户端 wg0 接口（症状：握手成功但 ping 不通服务端）。
	// peer.Address 存的格式是 172.16.7.2/32，这里把 /32 替换成子网掩码。
	clientAddr := peerAddressWithSubnetMask(peer.Address, cfg.WGSubnet)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "[Interface]\n")
	fmt.Fprintf(&buf, "PrivateKey = %s\n", peer.PrivateKey)
	fmt.Fprintf(&buf, "Address = %s\n", clientAddr)
	fmt.Fprintf(&buf, "DNS = %s\n", srvDNSIP)
	// MTU = 1280 是 IPv6 最小保证 MTU，避免移动网络/PPPoE/NAT 路径中
	// MTU 小于 1420 导致大包被丢弃
	fmt.Fprintf(&buf, "MTU = 1280\n\n")
	fmt.Fprintf(&buf, "[Peer]\n")
	fmt.Fprintf(&buf, "PublicKey = %s\n", srvPub)
	if peer.PresharedKey != "" {
		fmt.Fprintf(&buf, "PresharedKey = %s\n", peer.PresharedKey)
	}
	fmt.Fprintf(&buf, "Endpoint = %s:%d\n", serverEndpointHost, cfg.WGListenPort)
	fmt.Fprintf(&buf, "AllowedIPs = 0.0.0.0/0\n")
	fmt.Fprintf(&buf, "PersistentKeepalive = 25\n")
	return buf.String(), nil
}

// peerAddressWithSubnetMask 把 peer 的 /32 地址转换成带子网掩码的形式
// 输入: peerAddr="172.16.7.2/32", subnet="172.16.7.0/24"
// 输出: "172.16.7.2/24"
func peerAddressWithSubnetMask(peerAddr, subnet string) string {
	// 提取 peer 的 IP 部分
	ip := strings.Split(peerAddr, "/")[0]
	// 提取子网的掩码部分
	parts := strings.Split(subnet, "/")
	if len(parts) != 2 {
		return peerAddr // fallback
	}
	return fmt.Sprintf("%s/%s", ip, parts[1])
}

// 生成随机 ID（用于节点和 peer）
func GenerateID() string {
	b := make([]byte, 6)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}
